version: '3.8'

services:
    spl-source:
        build:
            context: .
            dockerfile: Dockerfile
        mem_limit: 256m
        image: spl-source:latest
        network_mode: host
        restart: always
